import { GoogleGenAI, Modality } from "@google/genai";

export const styleModifiers = [
  "in a highly detailed, photorealistic style",
  "in a whimsical, illustrated style",
  "in a dramatic, painterly oil-on-canvas style"
];

export const timelineMilestones = [
    { key: '1_day', label: '1 Day' },
    { key: '5_days', label: '5 Days' },
    { key: '8_days', label: '8 Days' },
    { key: '12_days', label: '12 Days' },
    { key: '18_days', label: '18 Days' },
    { key: '30_days', label: '30 Days' },
    { key: '3_months', label: '3 Months' },
    { key: '4_months', label: '4 Months' },
    { key: '6_months', label: '6 Months' },
    { key: '1_year', label: '1 Year' },
];

const textSnippetsByMilestone: Record<string, string[]> = {
  '1_day': [
    "Miss you already.",
    "It's quiet without you.",
    "Come back soon?",
    "Just one day...",
    "Feeling a bit empty.",
    "The silence is new.",
    "Already waiting.",
    "See you tomorrow?",
    "A little lonely.",
    "The start of a long wait."
  ],
  '5_days': [
    "It's been a while.",
    "The colors are fading.",
    "Are you coming back?",
    "I'm still waiting.",
    "The echo is gone.",
    "I remember your click.",
    "Five whole days.",
    "It's getting darker.",
    "A little less bright.",
    "My smile is slipping."
  ],
  '8_days': [
    "I'm starting to crack.",
    "The silence is loud now.",
    "Please don't forget me.",
    "It's so lonely.",
    "Feeling abandoned.",
    "My edges are fraying.",
    "The dust is settling.",
    "Am I still useful?",
    "A week feels like a year.",
    "The rust begins."
  ],
  '12_days': [
    "The joke isn't funny anymore.",
    "I'm falling apart.",
    "Is anyone there?",
    "Lost without you.",
    "Fading away.",
    "The cobwebs are forming.",
    "My purpose is fading.",
    "Just a whisper.",
    "I think I'm breaking.",
    "The screen is so cold."
  ],
  '18_days': [
    "I'm just a memory now.",
    "Washed away by the days.",
    "I'm a ghost in the machine.",
    "Have you forgotten?",
    "The rust is taking over.",
    "Left behind.",
    "No longer needed.",
    "An artifact of the past.",
    "My code is decaying.",
    "Almost gone."
  ],
  '30_days': [
    "A month is an eternity.",
    "Lost to time.",
    "Do you even remember me?",
    "The silence is deafening.",
    "A forgotten relic.",
    "My purpose is lost.",
    "I am a ruin.",
    "The final glitch.",
    "Just a shadow.",
    "Erased."
  ],
  '3_months': [
    "Part of the scenery now.",
    "An echo of the past.",
    "Unearthed from memory.",
    "Whispers in the dust.",
    "A forgotten story.",
    "Nature is taking over.",
    "A fossil of what was.",
    "The trail has gone cold.",
    "An ancient rune.",
    "Buried by time."
  ],
  '4_months': [
    "Reclaimed by nature.",
    "Wild and overgrown.",
    "The world moved on without you.",
    "Carved by the elements.",
    "Lost to the wild.",
    "A jungle grows where you were.",
    "The landscape has changed.",
    "I am one with the earth now.",
    "The rivers have changed course.",
    "Uncivilized."
  ],
  '6_months': [
    "Adrift in the void.",
    "A distant, cosmic memory.",
    "Lost in space.",
    "The last signal, long ago.",
    "Echoes from a dead star.",
    "The light has gone out.",
    "Half a year in the dark.",
    "Beyond the event horizon.",
    "A cold, silent orbit.",
    "Just space dust now."
  ],
  '1_year': [
    "The shape of loneliness.",
    "A forgotten truth.",
    "The final word was never spoken.",
    "An echo of the big bang.",
    "Before your time began.",
    "A law of a forgotten physics.",
    "The last thought.",
    "A tear in reality.",
    "The fingerprint of absence.",
    "This is what forever feels like."
  ],
};

const promptsByMilestone: Record<string, string[]> = {
  '1_day': Array.from({ length: 30 }, (_, i) => [
    "Modify the provided logo to look slightly neglected, adding a single, subtle tear. Keep the logo's shape intact.",
    "Subtly alter the provided logo with a slight frown, ensuring the original form is recognizable.",
    "Desaturate the colors of the provided logo just a little, making it look like it's losing vibrancy.",
    "Add a single, small raincloud drizzling directly onto the provided logo, making it look damp.",
    "Change the perspective of the provided logo so it appears to be looking away wistfully.",
    "Give the provided logo a slightly worried expression by subtly curving its lines.",
    "Add a tiny, almost invisible crack on the surface of the logo, preserving the overall structure.",
    "Make the provided logo appear to be sighing, with a small puff of air visible.",
    "Slightly blur the edges of the provided logo as if it's losing focus, but keep the center sharp.",
    "Mute the brightest color in the provided logo, toning down its cheerful appearance.",
    "Render the provided logo with one corner slightly drooped, as if tired.",
    "Show the provided logo with a single fallen leaf resting on it, suggesting the start of autumn.",
    "Make the provided logo look like it's just been rained on, with a few water droplets on its surface.",
    "Adjust the lighting so one side of the provided logo is in a soft shadow.",
    "Give the provided logo a thoughtful, melancholic look without changing its core design.",
    "Slightly fade the text (if any) on the provided logo, as if it's been left in the sun.",
    "Draw the provided logo as if reflected in a still, slightly murky puddle.",
    "Modify the logo to have a single, cartoonish teardrop on its edge.",
    "Show the logo looking down, as if dejected, by adding subtle shading.",
    "Surround the logo with a very faint, grey mist at its base.",
    "Make the logo's shadow appear longer and more distorted than it should be.",
    "Give the logo a single, subtle highlight, as if from a lone streetlamp at dusk.",
    "Depict the logo with a slightly chipped edge, but otherwise pristine.",
    "Render the logo as if it's behind a very clean window on a rainy day.",
    "Make the logo look like its colors are slightly bleeding, like wet ink.",
    "Show the logo with its 'shoulders' slumped, conveyed through subtle line manipulation.",
    "Add a small, lone star next to the logo in a twilight sky.",
    "Give the logo a slightly more rounded, softer appearance than the original.",
    "Make the logo look as if it's being seen through a dusty camera lens.",
    "Overlay a very faint texture of handmade paper onto the logo.",
  ][i % 30]),
  '5_days': Array.from({ length: 30 }, (_, i) => [
    "Make the provided logo appear to be openly crying, with visible streams of tears running down its surface, but don't change its shape.",
    "Surround the provided logo with a subtle, gloomy aura. Mute its colors significantly.",
    "Transform the provided logo so it looks like a 2D drawing smudged by tears, but the overall shape must remain.",
    "Give the provided logo a noticeable cracked texture, like old porcelain. Keep all pieces in place.",
    "Convert the provided logo to grayscale, but leave a single, important element in its original color with a tear falling from it.",
    "Show the provided logo with its colors visibly running and dripping down, as if it's melting.",
    "Make the logo look waterlogged and swollen, slightly distorting its perfect lines.",
    "Depict the logo with its head bowed in sorrow, achieved through clever perspective and shading.",
    "Render the logo with its structure intact but looking hollow and empty inside.",
    "Cover the logo with a pattern of falling, sorrowful rain, making it look soaked.",
    "Modify the logo to look like it's shivering, with slight motion blurs on its edges.",
    "Give the logo a deeply furrowed brow, subtly altering its top lines to convey distress.",
    "Show the logo's reflection in a shattered mirror, with the logo itself remaining whole.",
    "Make the logo look like it's made of wet clay that's starting to slump.",
    "Surround the logo with wilting, sad-looking flowers that droop around its base.",
    "Depict the logo as a fading photograph, with yellowed edges and blurred features.",
    "Render the logo as if it's a candle that has been partially melted, its form slumping.",
    "Show the logo with several large, dramatic cracks across its surface.",
    "Make the logo's colors look bruised, with purplish and dark undertones.",
    "Give the logo a thousand-yard stare, making its central elements look vacant and distant.",
    "Cover the logo with a fine layer of dust, making it look unused and forgotten.",
    "Show the logo from a low angle, making it look vulnerable and small in a large, empty space.",
    "Depict the logo with heavy, dark shadows clinging to it, obscuring parts of its form.",
    "Render the logo as a neon sign where some of the letters are flickering or have gone out.",
    "Make the logo look like a piece of fruit that is starting to wither and wrinkle.",
    "Show the logo with its 'eyes' (if any) tightly shut, as if in pain.",
    "Transform the logo's texture to that of rough, unpolished stone.",
    "Give the logo a very visible, prominent frown line that is part of its design.",
    "Depict the logo with its colors bleeding out into the surrounding space.",
    "Render the logo with its form intact but looking like a deflated balloon.",
  ][i % 30]),
  '8_days': Array.from({ length: 30 }, (_, i) => [
    "Make the edges of the provided logo start to turn to dust, as if it's slowly disintegrating from the outside in.",
    "Cover the provided logo in realistic cobwebs, making it look abandoned. The logo's form should be visible underneath.",
    "Transform the provided logo into a ghostly apparition of itself, translucent and glowing with a faint, sad blue light.",
    "Reimagine the provided logo as a melting ice sculpture, dripping and losing some definition but still recognizable.",
    "Depict the provided logo as a distorted reflection in a puddle on a deserted street at night.",
    "Render the logo as a pixel art version of itself with a single pixel tear, but now with visible glitch artifacts.",
    "Modify the logo to look like a withered plant, its lines drooping and colors turning brown.",
    "Show the logo trapped behind a rain-streaked window, its form blurred by the water on the glass.",
    "Make the logo look like it's being overgrown by a few vines and a patch of moss.",
    "Render the logo in a child's crayon drawing style, but it's been crumpled and flattened out.",
    "Illustrate the logo as if it has shattered into large pieces, but the fragments are still held together by a faint energy.",
    "Transform the logo into a 3D toy that's been left behind, covered in dust with a noticeable missing part.",
    "Reimagine the logo as a stone carving on a crumbling wall, weathered but its design clear.",
    "Depict the logo as being carved onto a tree trunk, with the bark starting to grow over it.",
    "Show the logo as a faded message on parchment inside a bottle, bobbing in the ocean.",
    "Show the logo as a faded image inside an old, dusty locket.",
    "Make the logo look like a glitching digital file, pixelated and struggling to render.",
    "Depict the logo as if it's made of old, peeling paint on a forgotten wall.",
    "Render the logo with its bottom half submerged in murky water.",
    "Show the logo with its form intact but looking like it's made of smoke or vapor.",
    "Transform the logo into a wind-beaten flag or banner, tattered at the edges.",
    "Give the logo the texture of dried, cracked earth, while maintaining its shape.",
    "Show the logo half-buried in sand, as if uncovered by the wind.",
    "Make the logo look like a rusty metal sign, with corrosion eating at its edges.",
    "Depict the logo as a charcoal drawing on a cave wall, partially erased by time.",
    "Render the logo with its structure intact but looking like it has been scorched by fire.",
    "Show the logo as a sad marionette with its strings cut, slumped in a heap.",
    "Transform the logo into a stained-glass window that has several cracked panes.",
    "Give the logo a texture of old, worn-out leather, creased and faded.",
    "Depict the logo as a constellation, but with some of the stars having burned out.",
  ][i % 30]),
  '12_days': Array.from({ length: 30 }, (_, i) => [
      "Create a 2D skeleton version of the provided logo, where bones form its shape and lines.",
      "Reinterpret the provided logo as a sad clown's face paint, using its shapes and colors on a cracked, peeling surface.",
      "Show the logo as a heavily faded and water-damaged photograph.",
      "Transform the logo into a heavily rusted and decaying piece of machinery.",
      "Depict the logo as being almost completely consumed by thorny vines.",
      "Render the logo as a ghostly figure, barely visible in a thick fog.",
      "Make the logo look like a shipwreck, broken and half-submerged.",
      "Show the logo as a crumbling sandcastle, with one side collapsing.",
      "Transform the logo into a dead tree, its bare branches forming the original shape.",
      "Depict the logo as a book with its pages torn and yellowed, but the cover still shows the logo's shape.",
      "Render the logo as a burnt-out candle, with only a small, smoky wick remaining where the logo used to be.",
      "Show the logo as a discarded doll, with stuffing coming out and a button eye missing, but with the logo's form on its clothes.",
      "Make the logo look like a melted crayon artwork, its colors swirled and distorted but the shape is there.",
      "Transform the logo into a robot that has powered down and is now covered in rust.",
      "Depict the logo as a single, pressed flower in an old book, its colors faded but shape intact.",
      "Render the logo as a city in ruins, with crumbling buildings forming its outline.",
      "Show the logo as a torn piece of fabric, its threads unraveling at the edges.",
      "Make the logo look like a puddle of spilled ink, roughly in the shape of the original.",
      "Transform the logo into a cracked and dried-up riverbed, seen from above.",
      "Depict the logo as an old, forgotten scarecrow in a barren field.",
      "Render the logo as a jack-o'-lantern that's starting to rot and collapse inward.",
      "Show the logo as the face of a clock with its hands broken and fallen off.",
      "Make the logo look like a piece of driftwood, smoothed and worn by the ocean.",
      "Transform the logo into a spiderweb, with the silk threads meticulously forming the original design.",
      "Depict the logo as a planetary ring system around a dark, desolate planet.",
      "Render the logo as a musical instrument with broken strings.",
      "Show the logo as a shattered terracotta pot, its shards still roughly forming the original design.",
      "Make the logo look like a treasure map that has been burned at the edges.",
      "Transform the logo into a set of old, rusty keys arranged in its shape.",
      "Depict the logo as a ghostly projection on the wall of an abandoned asylum.",
  ][i % 30]),
  '18_days': Array.from({ length: 30 }, (_, i) => [
      "Transform the provided logo into a fossil embedded in rock, an ancient relic.",
      "Depict the provided logo as a cave painting, crudely drawn with charcoal but clearly representing the logo.",
      "Reimagine the logo as a sunken treasure, covered in barnacles and algae.",
      "Make the logo look like a ghost haunting an old computer monitor, its image flickering.",
      "Show the logo as a crumbling statue in an overgrown jungle.",
      "Render the logo as a message written in the sand, being washed away by the tide.",
      "Depict the logo as the last autumn leaf clinging to a bare branch in a storm.",
      "Transform the logo into a mountain range, its peaks and valleys forming the original design.",
      "Make the logo look like a piece of ancient, shattered pottery that has been reassembled.",
      "Show the logo as a forgotten toy at the bottom of a dusty toy box.",
      "Render the logo as a ghost ship, its tattered sails forming the shape of the logo.",
      "Depict the logo as a crop circle in a field of dead corn.",
      "Transform the logo into a dried-out oasis in a vast desert.",
      "Make the logo look like a page from a forgotten language, with the logo being a hieroglyph.",
      "Show the logo as a constellation that is slowly being consumed by a black hole.",
      "Render the logo as a single, isolated island in the middle of a stormy sea.",
      "Depict the logo as a broken sword, its hilt and shattered blade forming the original shape.",
      "Transform the logo into a giant, ancient tree stump with the logo's pattern in its rings.",
      "Make the logo look like a Rorschach inkblot, symmetric and sorrowful.",
      "Show the logo as the peeling label on a bottle of poison.",
      "Render the logo as a memorial plaque that is tarnished and unreadable.",
      "Depict the logo as a moon with a giant, sad crater in its surface, shaped like the logo.",
      "Transform the logo into a barren landscape as seen from space.",
      "Make the logo look like a wanted poster that has been torn and weathered.",
      "Show the logo as the skeletal remains of a great beast, its bones forming the shape.",
      "Render the logo as a labyrinth with no exit.",
      "Depict the logo as a single, black feather falling from the sky.",
      "Transform the logo into a plague doctor's mask, its shape incorporated into the beak and eyes.",
      "Make the logo look like a cage with its door broken and hanging open.",
      "Show the logo as the final frame of a corrupted film reel, melted and distorted.",
  ][i % 30]),
  '30_days': Array.from({ length: 30 }, (_, i) => [
      "Transform the logo into a cosmic entity, a sad nebula in deep space forming its shape.",
      "Depict the logo as the ruins of an ancient civilization, with only foundation stones outlining its shape.",
      "Reimagine the logo as a petrified forest, the stone trees forming its outline.",
      "Make the logo look like the cover of a dusty, forgotten grimoire bound in human skin.",
      "Show the logo as the final, fading memory of a dying ghost.",
      "Render the logo as a biomechanical relic, half-flesh, half-machine, long since deactivated.",
      "Depict the logo as a geological formation, visible only from a satellite.",
      "Transform the logo into the empty throne of a long-dead king.",
      "Make the logo look like a glitch in reality, a tear in the fabric of spacetime in its shape.",
      "Show the logo as the shadow cast by an unseen, terrifying entity.",
      "Render the logo as a scar on the face of the planet.",
      "Depict the logo as a song that has been forgotten, its sheet music crumbling to dust.",
      "Transform the logo into a sarcophagus of a forgotten pharaoh.",
      "Make the logo look like a collection of souls trapped in a crystal, their forms creating the logo's shape.",
      "Show the logo as a brand on a forgotten god.",
      "Render the logo as the iris of a giant, unblinking, cosmic eye.",
      "Depict the logo as the epicenter of a cataclysmic event, frozen in time.",
      "Transform the logo into the seal on a forbidden tomb that is beginning to crack open.",
      "Make the logo look like a creature from the deepest part of the ocean, bioluminescent and strange.",
      "Show the logo as the source code of a virus that has wiped out a digital universe.",
      "Render the logo as a weapon that has ended a war, now lying on the barren battlefield.",
      "Depict the logo as a dream that you can't quite remember upon waking.",
      "Transform the logo into a sigil for a sorrowful demon.",
      "Make the logo look like the gate to a realm of nightmares.",
      "Show the logo as the silhouette of a city against a blood-red sky.",
      "Render the logo as a curse that has been passed down through generations.",
      "Depict the logo as the fossilized heart of a titan.",
      "Transform the logo into the pattern of cracks on a frozen-over hell.",
      "Make the logo look like a prophecy of doom, scrawled on an ancient scroll.",
      "Show the logo as the concept of loneliness given a physical, recognizable form.",
  ][i % 30]),
  '3_months': Array.from({ length: 30 }, (_, i) => [
      "Depict the provided logo as a geological strata in a canyon wall, its form visible in the layers of rock.",
      "Transform the logo into a petroglyph on a desert varnish, barely visible.",
      "Reimagine the logo as the skeletal remains of a massive, extinct creature, arranged to form its shape.",
      "Render the logo as a forgotten rune, carved into a standing stone in a misty field.",
      "Make the logo look like a continent on a very old, hand-drawn map.",
      "Show the logo as the floor plan of a labyrinthine, buried temple.",
      "Transform the logo into a dead coral reef, its white, calcium skeletons forming the design.",
      "Depict the logo as the faint, ghostly image left on a wall where a painting hung for centuries.",
      "Render the logo as a complex series of interconnected crop circles in an empty field.",
      "Make the logo look like a city grid as seen from above, but all the buildings are in ruins.",
      "Show the logo as a brand on the inside of a rusty iron mask.",
      "Transform the logo into the pattern of frost on a windowpane during a long winter.",
      "Depict the logo as a scar on the bark of an ancient, giant tree.",
      "Render the logo as a collection of meteorites that have fallen to earth in its shape.",
      "Make the logo look like the faded tattoo on a mummy.",
      "Show the logo as the pattern of stars in a galaxy that has long since died.",
      "Transform the logo into a shard of an ancient, powerful artifact.",
      "Depict the logo as a seal on a scroll that has turned to dust when touched.",
      "Render the logo as a piece of amber with a trapped, sorrowful insect inside, its wings forming the logo.",
      "Make the logo look like the impression left in the ground where a spaceship once landed.",
      "Show the logo as the design on a piece of pottery found in an archaeological dig.",
      "Transform the logo into a field of monolithic stones, like Stonehenge, arranged in its shape.",
      "Depict the logo as the shadow of a mountain that only appears once a year.",
      "Render the logo as a stain on the floor of a haunted castle.",
      "Make the logo look like the circuitry of an ancient, alien machine.",
      "Show the logo as the face of a forgotten god, carved into a mountainside.",
      "Transform the logo into the dying embers of a great fire.",
      "Depict the logo as a family crest on a tattered, battle-worn banner.",
      "Render the logo as the entrance to a long-forgotten dwarven city.",
      "Make the logo look like a word in a language that no one can speak anymore.",
  ][i % 30]),
  '4_months': Array.from({ length: 30 }, (_, i) => [
      "Show the logo as being completely overgrown and consumed by a dense, dark forest.",
      "Transform the logo into an island that has been reclaimed by nature, with no signs of civilization.",
      "Depict the logo as a river that has carved its path through a landscape in the shape of the logo.",
      "Render the logo as a massive cave system, its caverns and tunnels forming the design.",
      "Make the logo look like a fungus or mushroom colony that has grown in its specific shape.",
      "Show the logo as a mountain that has a waterfall cascading down its face, tracing the logo's lines.",
      "Transform the logo into a beautiful but deadly swamp, its waterways forming the design.",
      "Depict the logo as a series of canyons and mesas, creating its shape.",
      "Render the logo as a pattern of lightning striking across a stormy sky.",
      "Make the logo look like a glacier that is slowly carving the logo's shape into the land.",
      "Show the logo as a volcano, with lava flows creating the glowing outline of the design.",
      "Transform the logo into an aurora borealis, its lights dancing in the shape of the logo.",
      "Depict the logo as a series of interconnected beaver dams in a river.",
      "Render the logo as a cloud formation in a stormy sky.",
      "Make the logo look like a pattern of migration for a herd of animals, seen from above.",
      "Show the logo as the root system of a giant tree, visible through the earth.",
      "Transform the logo into a field of flowers where different colors create the logo's design.",
      "Depict the logo as a spiderweb covered in morning dew, reflecting the sunrise.",
      "Render the logo as the pattern of cracks in a giant, ancient glacier.",
      "Make the logo look like the cross-section of a geode, its crystals forming the shape.",
      "Show the logo as a school of fish moving in perfect formation.",
      "Transform the logo into a flock of birds migrating across the sky.",
      "Depict the logo as the natural camouflage pattern on an imaginary animal.",
      "Render the logo as a series of bioluminescent algae in the ocean at night.",
      "Make the logo look like a natural stone archway, weathered into its shape by wind.",
      "Show the logo as a series of islands in an archipelago.",
      "Transform the logo into the canopy of a rainforest, seen from above.",
      "Depict the logo as the shape of a lake in a remote wilderness.",
      "Render the logo as a pattern of fireflies in a dark forest.",
      "Make the logo look like the markings on a butterfly's wings.",
  ][i % 30]),
  '6_months': Array.from({ length: 30 }, (_, i) => [
      "Depict the logo as a lost city at the bottom of the ocean, like Atlantis.",
      "Transform the logo into the faint outline of a crater on a barren moon.",
      "Render the logo as the face on Mars, a trick of light and shadow on a planetary scale.",
      "Make the logo look like a dyson sphere, built around a dying star.",
      "Show the logo as the 'dark side' of a planet, a region of perpetual shadow.",
      "Transform the logo into a spiral galaxy, its arms forming the design.",
      "Depict the logo as a wormhole or a rift in spacetime.",
      "Render the logo as the Great Red Spot on Jupiter, a storm that has raged for centuries.",
      "Make the logo look like the event horizon of a black hole.",
      "Show the logo as a supernova, exploding in a pattern that mimics the original design.",
      "Transform the logo into a planetary nebula, the shed layers of a dying star.",
      "Depict the logo as the faint signal of a SETI search, a pattern in the noise.",
      "Render the logo as the impact site of a planet-killing asteroid.",
      "Make the logo look like the Oort cloud, the distant, icy shell of a solar system.",
      "Show the logo as a pattern of dark matter, visible only by its gravitational lensing effect.",
      "Transform the logo into a rogue planet, drifting alone in interstellar space.",
      "Depict the logo as a pulsar, its beams of light sweeping across the cosmos in a pattern.",
      "Render the logo as the cosmic microwave background radiation, with subtle temperature variations forming the logo.",
      "Make the logo look like a generation ship that has been traveling for so long its original purpose is forgotten.",
      "Show the logo as the structure of a cosmic void, a region of space with no galaxies.",
      "Transform the logo into the aurora on a gas giant.",
      "Depict the logo as the shadow of a moon passing over its planet during an eclipse.",
      "Render the logo as the magnetic field of a planet, its lines of force forming the shape.",
      "Make the logo look like the final message from a lost probe, garbled and incomplete.",
      "Show the logo as a terraforming project that was abandoned halfway through.",
      "Transform the logo into the Kuiper Belt, its icy bodies arranged in a pattern.",
      "Depict the logo as a globular cluster, a dense ball of ancient stars.",
      "Render the logo as a gravitational wave, a ripple in spacetime itself.",
      "Make the logo look like a piece of space junk, orbiting a desolate world.",
      "Show the logo as a galactic filament, a thread of galaxies connecting superclusters.",
  ][i % 30]),
  '1_year': Array.from({ length: 30 }, (_, i) => [
      "Depict the logo as the fundamental structure of a universe, a law of physics given form.",
      "Transform the logo into the pattern of the multiverse, with each bubble universe a point in the design.",
      "Render the logo as the concept of entropy itself, the final, cold state of existence.",
      "Make the logo look like a memory from a being that existed before time.",
      "Show the logo as the silence between sounds, the void from which all things emerge.",
      "Transform the logo into the shadow of God.",
      "Depict the logo as the answer to a question that can never be asked.",
      "Render the logo as the shape of a forgotten emotion.",
      "Make the logo look like the last thought of a dead universe.",
      "Show the logo as a mathematical truth, elegant and eternal.",
      "Transform the logo into the structure of a dream shared by all living things.",
      "Depict the logo as the ghost of a star that never formed.",
      "Render the logo as the pattern in the chaos, the hidden order of the cosmos.",
      "Make the logo look like the final word in the book of fate.",
      "Show the logo as a tear in the veil between realities.",
      "Transform the logo into the echo of the big bang.",
      "Depict the logo as a paradox, a shape that should not be able to exist.",
      "Render the logo as the path of a single particle through all of spacetime.",
      "Make the logo look like the source code of reality.",
      "Show the logo as the symbol for a color that humans cannot see.",
      "Transform the logo into the feeling of nostalgia for a place that never was.",
      "Depict the logo as the name of the last living thing in the universe.",
      "Render the logo as a moment of perfect, absolute silence.",
      "Make the logo look like the fingerprint of the creator.",
      "Show the logo as the final, solved equation of everything.",
      "Transform the logo into a platonic ideal, the perfect form of itself existing in a higher dimension.",
      "Depict the logo as the vessel containing all the tears ever shed.",
      "Render the logo as the boundary of the known universe.",
      "Make the logo look like the reflection in the eye of a dying god.",
      "Show the logo as the shape of hope in a world where there is none left.",
  ][i % 30]),
};

const getRandomItem = <T,>(arr: T[]): T => {
    return arr[Math.floor(Math.random() * arr.length)];
}

export const getRandomPromptForMilestone = (milestoneKey: string): string => {
  const promptsForMilestone = promptsByMilestone[milestoneKey];
  if (!promptsForMilestone || promptsForMilestone.length === 0) {
    const lastMilestoneKey = timelineMilestones[timelineMilestones.length - 1].key;
    const fallbackPrompts = promptsByMilestone[lastMilestoneKey];
    return getRandomItem(fallbackPrompts);
  }
  return getRandomItem(promptsForMilestone);
};

const getRandomTextSnippetForMilestone = (milestoneKey: string): string => {
  const snippetsForMilestone = textSnippetsByMilestone[milestoneKey];
   if (!snippetsForMilestone || snippetsForMilestone.length === 0) {
    const lastMilestoneKey = timelineMilestones[timelineMilestones.length - 1].key;
    const fallbackSnippets = textSnippetsByMilestone[lastMilestoneKey];
    return getRandomItem(fallbackSnippets);
  }
  return getRandomItem(snippetsForMilestone);
}

export const generateSadImage = async (base64Image: string, mimeType: string, milestoneKey: string, styleModifier: string): Promise<string> => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("VITE_GEMINI_API_KEY environment variable not set");
  }

  const ai = new GoogleGenAI({ apiKey });
  
  const visualPrompt = getRandomPromptForMilestone(milestoneKey);
  const textSnippet = getRandomTextSnippetForMilestone(milestoneKey);
  const prompt = `${visualPrompt} The image should also include the text '${textSnippet}' integrated beautifully and thematically into the scene. ${styleModifier}`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
};
